// -------------------------------------------------------------
// 
// File Name: C:\Users\earun\Desktop\dcm_new\dcm_4\alpha16b_data_transmitter.v
// Created: 2026-05-03 12:29:22
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: alpha16b_data_transmitter
// Source Path: dcm_4/PMDC_inv_hdl1/16b_data_transmitter
// Hierarchy Level: 1
// Model version: 1.21
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module alpha16b_data_transmitter
          (clk,
           reset,
           enb,
           b2,
           b1,
           b0,
           d_en,
           ia_out,
           w_out,
           In88,
           In90,
           In10,
           In87,
           In89,
           In91,
           data_out);


  input   clk;
  input   reset;
  input   enb;
  input   b2;
  input   b1;
  input   b0;
  input   d_en;
  input   signed [15:0] ia_out;  // sfix16_En12
  input   signed [15:0] w_out;  // sfix16_En12
  input   signed [15:0] In88;  // sfix16_En12
  input   signed [15:0] In90;  // sfix16_En12
  input   signed [15:0] In10;  // sfix16_En12
  input   signed [15:0] In87;  // sfix16_En12
  input   signed [15:0] In89;  // sfix16_En12
  input   signed [15:0] In91;  // sfix16_En12
  output  [15:0] data_out;  // uint16


  reg  [2:0] rd_147_reg;  // ufix1 [3]
  wire d_en_1;
  reg  b0_1;
  reg  b1_1;
  reg  b2_1;
  wire bit_slicer1_out1;  // ufix1
  wire bit_slicer1_out2;  // ufix1
  wire bit_slicer1_out3;  // ufix1
  wire bit_slicer1_out4;  // ufix1
  wire bit_slicer1_out5;  // ufix1
  wire bit_slicer1_out6;  // ufix1
  wire bit_slicer1_out7;  // ufix1
  wire bit_slicer1_out8;  // ufix1
  wire bit_slicer1_out9;  // ufix1
  wire bit_slicer1_out10;  // ufix1
  wire bit_slicer1_out11;  // ufix1
  wire bit_slicer1_out12;  // ufix1
  wire bit_slicer1_out13;  // ufix1
  wire bit_slicer1_out14;  // ufix1
  wire bit_slicer1_out15;  // ufix1
  wire bit_slicer1_out16;  // ufix1
  reg  bit_slicer1_out16_1;  // ufix1
  wire bit_slicer2_out1;  // ufix1
  wire bit_slicer2_out2;  // ufix1
  wire bit_slicer2_out3;  // ufix1
  wire bit_slicer2_out4;  // ufix1
  wire bit_slicer2_out5;  // ufix1
  wire bit_slicer2_out6;  // ufix1
  wire bit_slicer2_out7;  // ufix1
  wire bit_slicer2_out8;  // ufix1
  wire bit_slicer2_out9;  // ufix1
  wire bit_slicer2_out10;  // ufix1
  wire bit_slicer2_out11;  // ufix1
  wire bit_slicer2_out12;  // ufix1
  wire bit_slicer2_out13;  // ufix1
  wire bit_slicer2_out14;  // ufix1
  wire bit_slicer2_out15;  // ufix1
  wire bit_slicer2_out16;  // ufix1
  reg  bit_slicer2_out16_1;  // ufix1
  wire bit_slicer3_out1;  // ufix1
  wire bit_slicer3_out2;  // ufix1
  wire bit_slicer3_out3;  // ufix1
  wire bit_slicer3_out4;  // ufix1
  wire bit_slicer3_out5;  // ufix1
  wire bit_slicer3_out6;  // ufix1
  wire bit_slicer3_out7;  // ufix1
  wire bit_slicer3_out8;  // ufix1
  wire bit_slicer3_out9;  // ufix1
  wire bit_slicer3_out10;  // ufix1
  wire bit_slicer3_out11;  // ufix1
  wire bit_slicer3_out12;  // ufix1
  wire bit_slicer3_out13;  // ufix1
  wire bit_slicer3_out14;  // ufix1
  wire bit_slicer3_out15;  // ufix1
  wire bit_slicer3_out16;  // ufix1
  reg  bit_slicer3_out16_1;  // ufix1
  wire bit_slicer4_out1;  // ufix1
  wire bit_slicer4_out2;  // ufix1
  wire bit_slicer4_out3;  // ufix1
  wire bit_slicer4_out4;  // ufix1
  wire bit_slicer4_out5;  // ufix1
  wire bit_slicer4_out6;  // ufix1
  wire bit_slicer4_out7;  // ufix1
  wire bit_slicer4_out8;  // ufix1
  wire bit_slicer4_out9;  // ufix1
  wire bit_slicer4_out10;  // ufix1
  wire bit_slicer4_out11;  // ufix1
  wire bit_slicer4_out12;  // ufix1
  wire bit_slicer4_out13;  // ufix1
  wire bit_slicer4_out14;  // ufix1
  wire bit_slicer4_out15;  // ufix1
  wire bit_slicer4_out16;  // ufix1
  reg  bit_slicer4_out16_1;  // ufix1
  wire bit_slicer5_out1;  // ufix1
  wire bit_slicer5_out2;  // ufix1
  wire bit_slicer5_out3;  // ufix1
  wire bit_slicer5_out4;  // ufix1
  wire bit_slicer5_out5;  // ufix1
  wire bit_slicer5_out6;  // ufix1
  wire bit_slicer5_out7;  // ufix1
  wire bit_slicer5_out8;  // ufix1
  wire bit_slicer5_out9;  // ufix1
  wire bit_slicer5_out10;  // ufix1
  wire bit_slicer5_out11;  // ufix1
  wire bit_slicer5_out12;  // ufix1
  wire bit_slicer5_out13;  // ufix1
  wire bit_slicer5_out14;  // ufix1
  wire bit_slicer5_out15;  // ufix1
  wire bit_slicer5_out16;  // ufix1
  reg  bit_slicer5_out16_1;  // ufix1
  wire bit_slicer6_out1;  // ufix1
  wire bit_slicer6_out2;  // ufix1
  wire bit_slicer6_out3;  // ufix1
  wire bit_slicer6_out4;  // ufix1
  wire bit_slicer6_out5;  // ufix1
  wire bit_slicer6_out6;  // ufix1
  wire bit_slicer6_out7;  // ufix1
  wire bit_slicer6_out8;  // ufix1
  wire bit_slicer6_out9;  // ufix1
  wire bit_slicer6_out10;  // ufix1
  wire bit_slicer6_out11;  // ufix1
  wire bit_slicer6_out12;  // ufix1
  wire bit_slicer6_out13;  // ufix1
  wire bit_slicer6_out14;  // ufix1
  wire bit_slicer6_out15;  // ufix1
  wire bit_slicer6_out16;  // ufix1
  reg  bit_slicer6_out16_1;  // ufix1
  wire bit_slicer7_out1;  // ufix1
  wire bit_slicer7_out2;  // ufix1
  wire bit_slicer7_out3;  // ufix1
  wire bit_slicer7_out4;  // ufix1
  wire bit_slicer7_out5;  // ufix1
  wire bit_slicer7_out6;  // ufix1
  wire bit_slicer7_out7;  // ufix1
  wire bit_slicer7_out8;  // ufix1
  wire bit_slicer7_out9;  // ufix1
  wire bit_slicer7_out10;  // ufix1
  wire bit_slicer7_out11;  // ufix1
  wire bit_slicer7_out12;  // ufix1
  wire bit_slicer7_out13;  // ufix1
  wire bit_slicer7_out14;  // ufix1
  wire bit_slicer7_out15;  // ufix1
  wire bit_slicer7_out16;  // ufix1
  reg  bit_slicer7_out16_1;  // ufix1
  wire bit_slicer8_out1;  // ufix1
  wire bit_slicer8_out2;  // ufix1
  wire bit_slicer8_out3;  // ufix1
  wire bit_slicer8_out4;  // ufix1
  wire bit_slicer8_out5;  // ufix1
  wire bit_slicer8_out6;  // ufix1
  wire bit_slicer8_out7;  // ufix1
  wire bit_slicer8_out8;  // ufix1
  wire bit_slicer8_out9;  // ufix1
  wire bit_slicer8_out10;  // ufix1
  wire bit_slicer8_out11;  // ufix1
  wire bit_slicer8_out12;  // ufix1
  wire bit_slicer8_out13;  // ufix1
  wire bit_slicer8_out14;  // ufix1
  wire bit_slicer8_out15;  // ufix1
  wire bit_slicer8_out16;  // ufix1
  reg  bit_slicer8_out16_1;  // ufix1
  wire mux16_out1;
  reg  mux16_out1_1;
  reg  bit_slicer1_out15_1;  // ufix1
  reg  bit_slicer2_out15_1;  // ufix1
  reg  bit_slicer3_out15_1;  // ufix1
  reg  bit_slicer4_out15_1;  // ufix1
  reg  bit_slicer5_out15_1;  // ufix1
  reg  bit_slicer6_out15_1;  // ufix1
  reg  bit_slicer7_out15_1;  // ufix1
  reg  bit_slicer8_out15_1;  // ufix1
  wire mux15_out1;
  reg  mux15_out1_1;
  reg  bit_slicer1_out14_1;  // ufix1
  reg  bit_slicer2_out14_1;  // ufix1
  reg  bit_slicer3_out14_1;  // ufix1
  reg  bit_slicer4_out14_1;  // ufix1
  reg  bit_slicer5_out14_1;  // ufix1
  reg  bit_slicer6_out14_1;  // ufix1
  reg  bit_slicer7_out14_1;  // ufix1
  reg  bit_slicer8_out14_1;  // ufix1
  wire mux14_out1;
  reg  mux14_out1_1;
  reg  bit_slicer1_out13_1;  // ufix1
  reg  bit_slicer2_out13_1;  // ufix1
  reg  bit_slicer3_out13_1;  // ufix1
  reg  bit_slicer4_out13_1;  // ufix1
  reg  bit_slicer5_out13_1;  // ufix1
  reg  bit_slicer6_out13_1;  // ufix1
  reg  bit_slicer7_out13_1;  // ufix1
  reg  bit_slicer8_out13_1;  // ufix1
  wire mux13_out1;
  reg  mux13_out1_1;
  reg  bit_slicer1_out12_1;  // ufix1
  reg  bit_slicer2_out12_1;  // ufix1
  reg  bit_slicer3_out12_1;  // ufix1
  reg  bit_slicer4_out12_1;  // ufix1
  reg  bit_slicer5_out12_1;  // ufix1
  reg  bit_slicer6_out12_1;  // ufix1
  reg  bit_slicer7_out12_1;  // ufix1
  reg  bit_slicer8_out12_1;  // ufix1
  wire mux12_out1;
  reg  mux12_out1_1;
  reg  bit_slicer1_out11_1;  // ufix1
  reg  bit_slicer2_out11_1;  // ufix1
  reg  bit_slicer3_out11_1;  // ufix1
  reg  bit_slicer4_out11_1;  // ufix1
  reg  bit_slicer5_out11_1;  // ufix1
  reg  bit_slicer6_out11_1;  // ufix1
  reg  bit_slicer7_out11_1;  // ufix1
  reg  bit_slicer8_out11_1;  // ufix1
  wire mux11_out1;
  reg  mux11_out1_1;
  reg  bit_slicer1_out10_1;  // ufix1
  reg  bit_slicer2_out10_1;  // ufix1
  reg  bit_slicer3_out10_1;  // ufix1
  reg  bit_slicer4_out10_1;  // ufix1
  reg  bit_slicer5_out10_1;  // ufix1
  reg  bit_slicer6_out10_1;  // ufix1
  reg  bit_slicer7_out10_1;  // ufix1
  reg  bit_slicer8_out10_1;  // ufix1
  wire mux10_out1;
  reg  mux10_out1_1;
  reg  bit_slicer1_out9_1;  // ufix1
  reg  bit_slicer2_out9_1;  // ufix1
  reg  bit_slicer3_out9_1;  // ufix1
  reg  bit_slicer4_out9_1;  // ufix1
  reg  bit_slicer5_out9_1;  // ufix1
  reg  bit_slicer6_out9_1;  // ufix1
  reg  bit_slicer7_out9_1;  // ufix1
  reg  bit_slicer8_out9_1;  // ufix1
  wire mux9_out1;
  reg  mux9_out1_1;
  reg  bit_slicer1_out8_1;  // ufix1
  reg  bit_slicer2_out8_1;  // ufix1
  reg  bit_slicer3_out8_1;  // ufix1
  reg  bit_slicer4_out8_1;  // ufix1
  reg  bit_slicer5_out8_1;  // ufix1
  reg  bit_slicer6_out8_1;  // ufix1
  reg  bit_slicer7_out8_1;  // ufix1
  reg  bit_slicer8_out8_1;  // ufix1
  wire mux8_out1;
  reg  mux8_out1_1;
  reg  bit_slicer1_out7_1;  // ufix1
  reg  bit_slicer2_out7_1;  // ufix1
  reg  bit_slicer3_out7_1;  // ufix1
  reg  bit_slicer4_out7_1;  // ufix1
  reg  bit_slicer5_out7_1;  // ufix1
  reg  bit_slicer6_out7_1;  // ufix1
  reg  bit_slicer7_out7_1;  // ufix1
  reg  bit_slicer8_out7_1;  // ufix1
  wire mux7_out1;
  reg  mux7_out1_1;
  reg  bit_slicer1_out6_1;  // ufix1
  reg  bit_slicer2_out6_1;  // ufix1
  reg  bit_slicer3_out6_1;  // ufix1
  reg  bit_slicer4_out6_1;  // ufix1
  reg  bit_slicer5_out6_1;  // ufix1
  reg  bit_slicer6_out6_1;  // ufix1
  reg  bit_slicer7_out6_1;  // ufix1
  reg  bit_slicer8_out6_1;  // ufix1
  wire mux6_out1;
  reg  mux6_out1_1;
  reg  bit_slicer1_out5_1;  // ufix1
  reg  bit_slicer2_out5_1;  // ufix1
  reg  bit_slicer3_out5_1;  // ufix1
  reg  bit_slicer4_out5_1;  // ufix1
  reg  bit_slicer5_out5_1;  // ufix1
  reg  bit_slicer6_out5_1;  // ufix1
  reg  bit_slicer7_out5_1;  // ufix1
  reg  bit_slicer8_out5_1;  // ufix1
  wire mux5_out1;
  reg  mux5_out1_1;
  reg  bit_slicer1_out4_1;  // ufix1
  reg  bit_slicer2_out4_1;  // ufix1
  reg  bit_slicer3_out4_1;  // ufix1
  reg  bit_slicer4_out4_1;  // ufix1
  reg  bit_slicer5_out4_1;  // ufix1
  reg  bit_slicer6_out4_1;  // ufix1
  reg  bit_slicer7_out4_1;  // ufix1
  reg  bit_slicer8_out4_1;  // ufix1
  wire mux4_out1;
  reg  mux4_out1_1;
  reg  bit_slicer1_out3_1;  // ufix1
  reg  bit_slicer2_out3_1;  // ufix1
  reg  bit_slicer3_out3_1;  // ufix1
  reg  bit_slicer4_out3_1;  // ufix1
  reg  bit_slicer5_out3_1;  // ufix1
  reg  bit_slicer6_out3_1;  // ufix1
  reg  bit_slicer7_out3_1;  // ufix1
  reg  bit_slicer8_out3_1;  // ufix1
  wire mux3_out1;
  reg  mux3_out1_1;
  reg  bit_slicer1_out2_1;  // ufix1
  reg  bit_slicer2_out2_1;  // ufix1
  reg  bit_slicer3_out2_1;  // ufix1
  reg  bit_slicer4_out2_1;  // ufix1
  reg  bit_slicer5_out2_1;  // ufix1
  reg  bit_slicer6_out2_1;  // ufix1
  reg  bit_slicer7_out2_1;  // ufix1
  reg  bit_slicer8_out2_1;  // ufix1
  wire mux2_out1;
  reg  mux2_out1_1;
  reg  bit_slicer1_out1_1;  // ufix1
  reg  bit_slicer2_out1_1;  // ufix1
  reg  bit_slicer3_out1_1;  // ufix1
  reg  bit_slicer4_out1_1;  // ufix1
  reg  bit_slicer5_out1_1;  // ufix1
  reg  bit_slicer6_out1_1;  // ufix1
  reg  bit_slicer7_out1_1;  // ufix1
  reg  bit_slicer8_out1_1;  // ufix1
  wire mux1_out1;
  reg  mux1_out1_1;
  wire [15:0] y;  // uint16
  reg [15:0] Delay_One_Step30_ectrl;  // uint16
  wire [15:0] Delay_One_Step30_ectrl_1;  // uint16
  wire [15:0] Delay_One_Step30_out1;  // uint16
  reg [15:0] Delay_One_Step30_out1_1;  // uint16


  always @(posedge clk or posedge reset)
    begin : rd_147_process
      if (reset == 1'b1) begin
        rd_147_reg <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          rd_147_reg[0] <= d_en;
          rd_147_reg[32'sd2:32'sd1] <= rd_147_reg[32'sd1:32'sd0];
        end
      end
    end

  assign d_en_1 = rd_147_reg[2];


  always @(posedge clk or posedge reset)
    begin : rd_0_process
      if (reset == 1'b1) begin
        b0_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          b0_1 <= b0;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_1_process
      if (reset == 1'b1) begin
        b1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          b1_1 <= b1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_2_process
      if (reset == 1'b1) begin
        b2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          b2_1 <= b2;
        end
      end
    end


  bit_slicer1 u_bit_slicer1 (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .In1(ia_out),  // sfix16_En12
                             .y0(bit_slicer1_out1),  // ufix1
                             .y1(bit_slicer1_out2),  // ufix1
                             .y2(bit_slicer1_out3),  // ufix1
                             .y3(bit_slicer1_out4),  // ufix1
                             .y4(bit_slicer1_out5),  // ufix1
                             .y5(bit_slicer1_out6),  // ufix1
                             .y6(bit_slicer1_out7),  // ufix1
                             .y7(bit_slicer1_out8),  // ufix1
                             .y8(bit_slicer1_out9),  // ufix1
                             .y9(bit_slicer1_out10),  // ufix1
                             .y10(bit_slicer1_out11),  // ufix1
                             .y11(bit_slicer1_out12),  // ufix1
                             .y12(bit_slicer1_out13),  // ufix1
                             .y13(bit_slicer1_out14),  // ufix1
                             .y14(bit_slicer1_out15),  // ufix1
                             .y15(bit_slicer1_out16)  // ufix1
                             );
  always @(posedge clk or posedge reset)
    begin : rd_3_process
      if (reset == 1'b1) begin
        bit_slicer1_out16_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out16_1 <= bit_slicer1_out16;
        end
      end
    end


  bit_slicer2 u_bit_slicer2 (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .In1(w_out),  // sfix16_En12
                             .y0(bit_slicer2_out1),  // ufix1
                             .y1(bit_slicer2_out2),  // ufix1
                             .y2(bit_slicer2_out3),  // ufix1
                             .y3(bit_slicer2_out4),  // ufix1
                             .y4(bit_slicer2_out5),  // ufix1
                             .y5(bit_slicer2_out6),  // ufix1
                             .y6(bit_slicer2_out7),  // ufix1
                             .y7(bit_slicer2_out8),  // ufix1
                             .y8(bit_slicer2_out9),  // ufix1
                             .y9(bit_slicer2_out10),  // ufix1
                             .y10(bit_slicer2_out11),  // ufix1
                             .y11(bit_slicer2_out12),  // ufix1
                             .y12(bit_slicer2_out13),  // ufix1
                             .y13(bit_slicer2_out14),  // ufix1
                             .y14(bit_slicer2_out15),  // ufix1
                             .y15(bit_slicer2_out16)  // ufix1
                             );
  always @(posedge clk or posedge reset)
    begin : rd_4_process
      if (reset == 1'b1) begin
        bit_slicer2_out16_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out16_1 <= bit_slicer2_out16;
        end
      end
    end


  bit_slicer3 u_bit_slicer3 (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .In1(In88),  // sfix16_En12
                             .y0(bit_slicer3_out1),  // ufix1
                             .y1(bit_slicer3_out2),  // ufix1
                             .y2(bit_slicer3_out3),  // ufix1
                             .y3(bit_slicer3_out4),  // ufix1
                             .y4(bit_slicer3_out5),  // ufix1
                             .y5(bit_slicer3_out6),  // ufix1
                             .y6(bit_slicer3_out7),  // ufix1
                             .y7(bit_slicer3_out8),  // ufix1
                             .y8(bit_slicer3_out9),  // ufix1
                             .y9(bit_slicer3_out10),  // ufix1
                             .y10(bit_slicer3_out11),  // ufix1
                             .y11(bit_slicer3_out12),  // ufix1
                             .y12(bit_slicer3_out13),  // ufix1
                             .y13(bit_slicer3_out14),  // ufix1
                             .y14(bit_slicer3_out15),  // ufix1
                             .y15(bit_slicer3_out16)  // ufix1
                             );
  always @(posedge clk or posedge reset)
    begin : rd_5_process
      if (reset == 1'b1) begin
        bit_slicer3_out16_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out16_1 <= bit_slicer3_out16;
        end
      end
    end


  bit_slicer4 u_bit_slicer4 (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .In1(In90),  // sfix16_En12
                             .y0(bit_slicer4_out1),  // ufix1
                             .y1(bit_slicer4_out2),  // ufix1
                             .y2(bit_slicer4_out3),  // ufix1
                             .y3(bit_slicer4_out4),  // ufix1
                             .y4(bit_slicer4_out5),  // ufix1
                             .y5(bit_slicer4_out6),  // ufix1
                             .y6(bit_slicer4_out7),  // ufix1
                             .y7(bit_slicer4_out8),  // ufix1
                             .y8(bit_slicer4_out9),  // ufix1
                             .y9(bit_slicer4_out10),  // ufix1
                             .y10(bit_slicer4_out11),  // ufix1
                             .y11(bit_slicer4_out12),  // ufix1
                             .y12(bit_slicer4_out13),  // ufix1
                             .y13(bit_slicer4_out14),  // ufix1
                             .y14(bit_slicer4_out15),  // ufix1
                             .y15(bit_slicer4_out16)  // ufix1
                             );
  always @(posedge clk or posedge reset)
    begin : rd_6_process
      if (reset == 1'b1) begin
        bit_slicer4_out16_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out16_1 <= bit_slicer4_out16;
        end
      end
    end


  bit_slicer5 u_bit_slicer5 (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .In1(In10),  // sfix16_En12
                             .y0(bit_slicer5_out1),  // ufix1
                             .y1(bit_slicer5_out2),  // ufix1
                             .y2(bit_slicer5_out3),  // ufix1
                             .y3(bit_slicer5_out4),  // ufix1
                             .y4(bit_slicer5_out5),  // ufix1
                             .y5(bit_slicer5_out6),  // ufix1
                             .y6(bit_slicer5_out7),  // ufix1
                             .y7(bit_slicer5_out8),  // ufix1
                             .y8(bit_slicer5_out9),  // ufix1
                             .y9(bit_slicer5_out10),  // ufix1
                             .y10(bit_slicer5_out11),  // ufix1
                             .y11(bit_slicer5_out12),  // ufix1
                             .y12(bit_slicer5_out13),  // ufix1
                             .y13(bit_slicer5_out14),  // ufix1
                             .y14(bit_slicer5_out15),  // ufix1
                             .y15(bit_slicer5_out16)  // ufix1
                             );
  always @(posedge clk or posedge reset)
    begin : rd_7_process
      if (reset == 1'b1) begin
        bit_slicer5_out16_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out16_1 <= bit_slicer5_out16;
        end
      end
    end


  bit_slicer6 u_bit_slicer6 (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .In1(In87),  // sfix16_En12
                             .y0(bit_slicer6_out1),  // ufix1
                             .y1(bit_slicer6_out2),  // ufix1
                             .y2(bit_slicer6_out3),  // ufix1
                             .y3(bit_slicer6_out4),  // ufix1
                             .y4(bit_slicer6_out5),  // ufix1
                             .y5(bit_slicer6_out6),  // ufix1
                             .y6(bit_slicer6_out7),  // ufix1
                             .y7(bit_slicer6_out8),  // ufix1
                             .y8(bit_slicer6_out9),  // ufix1
                             .y9(bit_slicer6_out10),  // ufix1
                             .y10(bit_slicer6_out11),  // ufix1
                             .y11(bit_slicer6_out12),  // ufix1
                             .y12(bit_slicer6_out13),  // ufix1
                             .y13(bit_slicer6_out14),  // ufix1
                             .y14(bit_slicer6_out15),  // ufix1
                             .y15(bit_slicer6_out16)  // ufix1
                             );
  always @(posedge clk or posedge reset)
    begin : rd_8_process
      if (reset == 1'b1) begin
        bit_slicer6_out16_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out16_1 <= bit_slicer6_out16;
        end
      end
    end


  bit_slicer7 u_bit_slicer7 (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .In1(In89),  // sfix16_En12
                             .y0(bit_slicer7_out1),  // ufix1
                             .y1(bit_slicer7_out2),  // ufix1
                             .y2(bit_slicer7_out3),  // ufix1
                             .y3(bit_slicer7_out4),  // ufix1
                             .y4(bit_slicer7_out5),  // ufix1
                             .y5(bit_slicer7_out6),  // ufix1
                             .y6(bit_slicer7_out7),  // ufix1
                             .y7(bit_slicer7_out8),  // ufix1
                             .y8(bit_slicer7_out9),  // ufix1
                             .y9(bit_slicer7_out10),  // ufix1
                             .y10(bit_slicer7_out11),  // ufix1
                             .y11(bit_slicer7_out12),  // ufix1
                             .y12(bit_slicer7_out13),  // ufix1
                             .y13(bit_slicer7_out14),  // ufix1
                             .y14(bit_slicer7_out15),  // ufix1
                             .y15(bit_slicer7_out16)  // ufix1
                             );
  always @(posedge clk or posedge reset)
    begin : rd_9_process
      if (reset == 1'b1) begin
        bit_slicer7_out16_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out16_1 <= bit_slicer7_out16;
        end
      end
    end


  bit_slicer8 u_bit_slicer8 (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .In1(In91),  // sfix16_En12
                             .y0(bit_slicer8_out1),  // ufix1
                             .y1(bit_slicer8_out2),  // ufix1
                             .y2(bit_slicer8_out3),  // ufix1
                             .y3(bit_slicer8_out4),  // ufix1
                             .y4(bit_slicer8_out5),  // ufix1
                             .y5(bit_slicer8_out6),  // ufix1
                             .y6(bit_slicer8_out7),  // ufix1
                             .y7(bit_slicer8_out8),  // ufix1
                             .y8(bit_slicer8_out9),  // ufix1
                             .y9(bit_slicer8_out10),  // ufix1
                             .y10(bit_slicer8_out11),  // ufix1
                             .y11(bit_slicer8_out12),  // ufix1
                             .y12(bit_slicer8_out13),  // ufix1
                             .y13(bit_slicer8_out14),  // ufix1
                             .y14(bit_slicer8_out15),  // ufix1
                             .y15(bit_slicer8_out16)  // ufix1
                             );
  always @(posedge clk or posedge reset)
    begin : rd_10_process
      if (reset == 1'b1) begin
        bit_slicer8_out16_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out16_1 <= bit_slicer8_out16;
        end
      end
    end


  mux16 u_mux16 (.b0(b0_1),
                 .b1(b1_1),
                 .b2(b2_1),
                 .d1(bit_slicer1_out16_1),  // ufix1
                 .d2(bit_slicer2_out16_1),  // ufix1
                 .d3(bit_slicer3_out16_1),  // ufix1
                 .d4(bit_slicer4_out16_1),  // ufix1
                 .d5(bit_slicer5_out16_1),  // ufix1
                 .d6(bit_slicer6_out16_1),  // ufix1
                 .d7(bit_slicer7_out16_1),  // ufix1
                 .d8(bit_slicer8_out16_1),  // ufix1
                 .data_out1(mux16_out1)
                 );
  always @(posedge clk or posedge reset)
    begin : rd_11_process
      if (reset == 1'b1) begin
        mux16_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux16_out1_1 <= mux16_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_12_process
      if (reset == 1'b1) begin
        bit_slicer1_out15_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out15_1 <= bit_slicer1_out15;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_13_process
      if (reset == 1'b1) begin
        bit_slicer2_out15_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out15_1 <= bit_slicer2_out15;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_14_process
      if (reset == 1'b1) begin
        bit_slicer3_out15_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out15_1 <= bit_slicer3_out15;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_15_process
      if (reset == 1'b1) begin
        bit_slicer4_out15_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out15_1 <= bit_slicer4_out15;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_16_process
      if (reset == 1'b1) begin
        bit_slicer5_out15_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out15_1 <= bit_slicer5_out15;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_17_process
      if (reset == 1'b1) begin
        bit_slicer6_out15_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out15_1 <= bit_slicer6_out15;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_18_process
      if (reset == 1'b1) begin
        bit_slicer7_out15_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out15_1 <= bit_slicer7_out15;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_19_process
      if (reset == 1'b1) begin
        bit_slicer8_out15_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out15_1 <= bit_slicer8_out15;
        end
      end
    end


  mux15 u_mux15 (.b0(b0_1),
                 .b1(b1_1),
                 .b2(b2_1),
                 .d1(bit_slicer1_out15_1),  // ufix1
                 .d2(bit_slicer2_out15_1),  // ufix1
                 .d3(bit_slicer3_out15_1),  // ufix1
                 .d4(bit_slicer4_out15_1),  // ufix1
                 .d5(bit_slicer5_out15_1),  // ufix1
                 .d6(bit_slicer6_out15_1),  // ufix1
                 .d7(bit_slicer7_out15_1),  // ufix1
                 .d8(bit_slicer8_out15_1),  // ufix1
                 .data_out1(mux15_out1)
                 );
  always @(posedge clk or posedge reset)
    begin : rd_20_process
      if (reset == 1'b1) begin
        mux15_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux15_out1_1 <= mux15_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_21_process
      if (reset == 1'b1) begin
        bit_slicer1_out14_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out14_1 <= bit_slicer1_out14;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_22_process
      if (reset == 1'b1) begin
        bit_slicer2_out14_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out14_1 <= bit_slicer2_out14;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_23_process
      if (reset == 1'b1) begin
        bit_slicer3_out14_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out14_1 <= bit_slicer3_out14;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_24_process
      if (reset == 1'b1) begin
        bit_slicer4_out14_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out14_1 <= bit_slicer4_out14;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_25_process
      if (reset == 1'b1) begin
        bit_slicer5_out14_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out14_1 <= bit_slicer5_out14;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_26_process
      if (reset == 1'b1) begin
        bit_slicer6_out14_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out14_1 <= bit_slicer6_out14;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_27_process
      if (reset == 1'b1) begin
        bit_slicer7_out14_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out14_1 <= bit_slicer7_out14;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_28_process
      if (reset == 1'b1) begin
        bit_slicer8_out14_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out14_1 <= bit_slicer8_out14;
        end
      end
    end


  mux14 u_mux14 (.b0(b0_1),
                 .b1(b1_1),
                 .b2(b2_1),
                 .d1(bit_slicer1_out14_1),  // ufix1
                 .d2(bit_slicer2_out14_1),  // ufix1
                 .d3(bit_slicer3_out14_1),  // ufix1
                 .d4(bit_slicer4_out14_1),  // ufix1
                 .d5(bit_slicer5_out14_1),  // ufix1
                 .d6(bit_slicer6_out14_1),  // ufix1
                 .d7(bit_slicer7_out14_1),  // ufix1
                 .d8(bit_slicer8_out14_1),  // ufix1
                 .data_out1(mux14_out1)
                 );
  always @(posedge clk or posedge reset)
    begin : rd_29_process
      if (reset == 1'b1) begin
        mux14_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux14_out1_1 <= mux14_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_30_process
      if (reset == 1'b1) begin
        bit_slicer1_out13_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out13_1 <= bit_slicer1_out13;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_31_process
      if (reset == 1'b1) begin
        bit_slicer2_out13_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out13_1 <= bit_slicer2_out13;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_32_process
      if (reset == 1'b1) begin
        bit_slicer3_out13_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out13_1 <= bit_slicer3_out13;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_33_process
      if (reset == 1'b1) begin
        bit_slicer4_out13_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out13_1 <= bit_slicer4_out13;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_34_process
      if (reset == 1'b1) begin
        bit_slicer5_out13_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out13_1 <= bit_slicer5_out13;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_35_process
      if (reset == 1'b1) begin
        bit_slicer6_out13_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out13_1 <= bit_slicer6_out13;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_36_process
      if (reset == 1'b1) begin
        bit_slicer7_out13_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out13_1 <= bit_slicer7_out13;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_37_process
      if (reset == 1'b1) begin
        bit_slicer8_out13_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out13_1 <= bit_slicer8_out13;
        end
      end
    end


  mux13 u_mux13 (.b0(b0_1),
                 .b1(b1_1),
                 .b2(b2_1),
                 .d1(bit_slicer1_out13_1),  // ufix1
                 .d2(bit_slicer2_out13_1),  // ufix1
                 .d3(bit_slicer3_out13_1),  // ufix1
                 .d4(bit_slicer4_out13_1),  // ufix1
                 .d5(bit_slicer5_out13_1),  // ufix1
                 .d6(bit_slicer6_out13_1),  // ufix1
                 .d7(bit_slicer7_out13_1),  // ufix1
                 .d8(bit_slicer8_out13_1),  // ufix1
                 .Out1(mux13_out1)
                 );
  always @(posedge clk or posedge reset)
    begin : rd_38_process
      if (reset == 1'b1) begin
        mux13_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux13_out1_1 <= mux13_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_39_process
      if (reset == 1'b1) begin
        bit_slicer1_out12_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out12_1 <= bit_slicer1_out12;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_40_process
      if (reset == 1'b1) begin
        bit_slicer2_out12_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out12_1 <= bit_slicer2_out12;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_41_process
      if (reset == 1'b1) begin
        bit_slicer3_out12_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out12_1 <= bit_slicer3_out12;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_42_process
      if (reset == 1'b1) begin
        bit_slicer4_out12_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out12_1 <= bit_slicer4_out12;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_43_process
      if (reset == 1'b1) begin
        bit_slicer5_out12_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out12_1 <= bit_slicer5_out12;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_44_process
      if (reset == 1'b1) begin
        bit_slicer6_out12_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out12_1 <= bit_slicer6_out12;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_45_process
      if (reset == 1'b1) begin
        bit_slicer7_out12_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out12_1 <= bit_slicer7_out12;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_46_process
      if (reset == 1'b1) begin
        bit_slicer8_out12_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out12_1 <= bit_slicer8_out12;
        end
      end
    end


  mux12 u_mux12 (.b0(b0_1),
                 .b1(b1_1),
                 .b2(b2_1),
                 .d1(bit_slicer1_out12_1),  // ufix1
                 .d2(bit_slicer2_out12_1),  // ufix1
                 .d3(bit_slicer3_out12_1),  // ufix1
                 .d4(bit_slicer4_out12_1),  // ufix1
                 .d5(bit_slicer5_out12_1),  // ufix1
                 .d6(bit_slicer6_out12_1),  // ufix1
                 .d7(bit_slicer7_out12_1),  // ufix1
                 .d8(bit_slicer8_out12_1),  // ufix1
                 .data_out1(mux12_out1)
                 );
  always @(posedge clk or posedge reset)
    begin : rd_47_process
      if (reset == 1'b1) begin
        mux12_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux12_out1_1 <= mux12_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_48_process
      if (reset == 1'b1) begin
        bit_slicer1_out11_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out11_1 <= bit_slicer1_out11;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_49_process
      if (reset == 1'b1) begin
        bit_slicer2_out11_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out11_1 <= bit_slicer2_out11;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_50_process
      if (reset == 1'b1) begin
        bit_slicer3_out11_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out11_1 <= bit_slicer3_out11;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_51_process
      if (reset == 1'b1) begin
        bit_slicer4_out11_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out11_1 <= bit_slicer4_out11;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_52_process
      if (reset == 1'b1) begin
        bit_slicer5_out11_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out11_1 <= bit_slicer5_out11;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_53_process
      if (reset == 1'b1) begin
        bit_slicer6_out11_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out11_1 <= bit_slicer6_out11;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_54_process
      if (reset == 1'b1) begin
        bit_slicer7_out11_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out11_1 <= bit_slicer7_out11;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_55_process
      if (reset == 1'b1) begin
        bit_slicer8_out11_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out11_1 <= bit_slicer8_out11;
        end
      end
    end


  mux11 u_mux11 (.b0(b0_1),
                 .b1(b1_1),
                 .b2(b2_1),
                 .d1(bit_slicer1_out11_1),  // ufix1
                 .d2(bit_slicer2_out11_1),  // ufix1
                 .d3(bit_slicer3_out11_1),  // ufix1
                 .d4(bit_slicer4_out11_1),  // ufix1
                 .d5(bit_slicer5_out11_1),  // ufix1
                 .d6(bit_slicer6_out11_1),  // ufix1
                 .d7(bit_slicer7_out11_1),  // ufix1
                 .d8(bit_slicer8_out11_1),  // ufix1
                 .data_out1(mux11_out1)
                 );
  always @(posedge clk or posedge reset)
    begin : rd_56_process
      if (reset == 1'b1) begin
        mux11_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux11_out1_1 <= mux11_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_57_process
      if (reset == 1'b1) begin
        bit_slicer1_out10_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out10_1 <= bit_slicer1_out10;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_58_process
      if (reset == 1'b1) begin
        bit_slicer2_out10_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out10_1 <= bit_slicer2_out10;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_59_process
      if (reset == 1'b1) begin
        bit_slicer3_out10_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out10_1 <= bit_slicer3_out10;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_60_process
      if (reset == 1'b1) begin
        bit_slicer4_out10_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out10_1 <= bit_slicer4_out10;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_61_process
      if (reset == 1'b1) begin
        bit_slicer5_out10_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out10_1 <= bit_slicer5_out10;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_62_process
      if (reset == 1'b1) begin
        bit_slicer6_out10_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out10_1 <= bit_slicer6_out10;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_63_process
      if (reset == 1'b1) begin
        bit_slicer7_out10_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out10_1 <= bit_slicer7_out10;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_64_process
      if (reset == 1'b1) begin
        bit_slicer8_out10_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out10_1 <= bit_slicer8_out10;
        end
      end
    end


  mux10 u_mux10 (.b0(b0_1),
                 .b1(b1_1),
                 .b2(b2_1),
                 .d1(bit_slicer1_out10_1),  // ufix1
                 .d2(bit_slicer2_out10_1),  // ufix1
                 .d3(bit_slicer3_out10_1),  // ufix1
                 .d4(bit_slicer4_out10_1),  // ufix1
                 .d5(bit_slicer5_out10_1),  // ufix1
                 .d6(bit_slicer6_out10_1),  // ufix1
                 .d7(bit_slicer7_out10_1),  // ufix1
                 .d8(bit_slicer8_out10_1),  // ufix1
                 .data_out1(mux10_out1)
                 );
  always @(posedge clk or posedge reset)
    begin : rd_65_process
      if (reset == 1'b1) begin
        mux10_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux10_out1_1 <= mux10_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_66_process
      if (reset == 1'b1) begin
        bit_slicer1_out9_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out9_1 <= bit_slicer1_out9;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_67_process
      if (reset == 1'b1) begin
        bit_slicer2_out9_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out9_1 <= bit_slicer2_out9;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_68_process
      if (reset == 1'b1) begin
        bit_slicer3_out9_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out9_1 <= bit_slicer3_out9;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_69_process
      if (reset == 1'b1) begin
        bit_slicer4_out9_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out9_1 <= bit_slicer4_out9;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_70_process
      if (reset == 1'b1) begin
        bit_slicer5_out9_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out9_1 <= bit_slicer5_out9;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_71_process
      if (reset == 1'b1) begin
        bit_slicer6_out9_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out9_1 <= bit_slicer6_out9;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_72_process
      if (reset == 1'b1) begin
        bit_slicer7_out9_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out9_1 <= bit_slicer7_out9;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_73_process
      if (reset == 1'b1) begin
        bit_slicer8_out9_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out9_1 <= bit_slicer8_out9;
        end
      end
    end


  mux9 u_mux9 (.b0(b0_1),
               .b1(b1_1),
               .b2(b2_1),
               .d1(bit_slicer1_out9_1),  // ufix1
               .d2(bit_slicer2_out9_1),  // ufix1
               .d3(bit_slicer3_out9_1),  // ufix1
               .d4(bit_slicer4_out9_1),  // ufix1
               .d5(bit_slicer5_out9_1),  // ufix1
               .d6(bit_slicer6_out9_1),  // ufix1
               .d7(bit_slicer7_out9_1),  // ufix1
               .d8(bit_slicer8_out9_1),  // ufix1
               .Out1(mux9_out1)
               );
  always @(posedge clk or posedge reset)
    begin : rd_74_process
      if (reset == 1'b1) begin
        mux9_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux9_out1_1 <= mux9_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_75_process
      if (reset == 1'b1) begin
        bit_slicer1_out8_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out8_1 <= bit_slicer1_out8;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_76_process
      if (reset == 1'b1) begin
        bit_slicer2_out8_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out8_1 <= bit_slicer2_out8;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_77_process
      if (reset == 1'b1) begin
        bit_slicer3_out8_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out8_1 <= bit_slicer3_out8;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_78_process
      if (reset == 1'b1) begin
        bit_slicer4_out8_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out8_1 <= bit_slicer4_out8;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_79_process
      if (reset == 1'b1) begin
        bit_slicer5_out8_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out8_1 <= bit_slicer5_out8;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_80_process
      if (reset == 1'b1) begin
        bit_slicer6_out8_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out8_1 <= bit_slicer6_out8;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_81_process
      if (reset == 1'b1) begin
        bit_slicer7_out8_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out8_1 <= bit_slicer7_out8;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_82_process
      if (reset == 1'b1) begin
        bit_slicer8_out8_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out8_1 <= bit_slicer8_out8;
        end
      end
    end


  mux8 u_mux8 (.b0(b0_1),
               .b1(b1_1),
               .b2(b2_1),
               .d1(bit_slicer1_out8_1),  // ufix1
               .d2(bit_slicer2_out8_1),  // ufix1
               .d3(bit_slicer3_out8_1),  // ufix1
               .d4(bit_slicer4_out8_1),  // ufix1
               .d5(bit_slicer5_out8_1),  // ufix1
               .d6(bit_slicer6_out8_1),  // ufix1
               .d7(bit_slicer7_out8_1),  // ufix1
               .d8(bit_slicer8_out8_1),  // ufix1
               .data_out1(mux8_out1)
               );
  always @(posedge clk or posedge reset)
    begin : rd_83_process
      if (reset == 1'b1) begin
        mux8_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux8_out1_1 <= mux8_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_84_process
      if (reset == 1'b1) begin
        bit_slicer1_out7_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out7_1 <= bit_slicer1_out7;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_85_process
      if (reset == 1'b1) begin
        bit_slicer2_out7_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out7_1 <= bit_slicer2_out7;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_86_process
      if (reset == 1'b1) begin
        bit_slicer3_out7_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out7_1 <= bit_slicer3_out7;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_87_process
      if (reset == 1'b1) begin
        bit_slicer4_out7_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out7_1 <= bit_slicer4_out7;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_88_process
      if (reset == 1'b1) begin
        bit_slicer5_out7_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out7_1 <= bit_slicer5_out7;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_89_process
      if (reset == 1'b1) begin
        bit_slicer6_out7_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out7_1 <= bit_slicer6_out7;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_90_process
      if (reset == 1'b1) begin
        bit_slicer7_out7_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out7_1 <= bit_slicer7_out7;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_91_process
      if (reset == 1'b1) begin
        bit_slicer8_out7_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out7_1 <= bit_slicer8_out7;
        end
      end
    end


  mux7 u_mux7 (.b0(b0_1),
               .b1(b1_1),
               .b2(b2_1),
               .d1(bit_slicer1_out7_1),  // ufix1
               .d2(bit_slicer2_out7_1),  // ufix1
               .d3(bit_slicer3_out7_1),  // ufix1
               .d4(bit_slicer4_out7_1),  // ufix1
               .d5(bit_slicer5_out7_1),  // ufix1
               .d6(bit_slicer6_out7_1),  // ufix1
               .d7(bit_slicer7_out7_1),  // ufix1
               .d8(bit_slicer8_out7_1),  // ufix1
               .data_out1(mux7_out1)
               );
  always @(posedge clk or posedge reset)
    begin : rd_92_process
      if (reset == 1'b1) begin
        mux7_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux7_out1_1 <= mux7_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_93_process
      if (reset == 1'b1) begin
        bit_slicer1_out6_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out6_1 <= bit_slicer1_out6;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_94_process
      if (reset == 1'b1) begin
        bit_slicer2_out6_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out6_1 <= bit_slicer2_out6;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_95_process
      if (reset == 1'b1) begin
        bit_slicer3_out6_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out6_1 <= bit_slicer3_out6;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_96_process
      if (reset == 1'b1) begin
        bit_slicer4_out6_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out6_1 <= bit_slicer4_out6;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_97_process
      if (reset == 1'b1) begin
        bit_slicer5_out6_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out6_1 <= bit_slicer5_out6;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_98_process
      if (reset == 1'b1) begin
        bit_slicer6_out6_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out6_1 <= bit_slicer6_out6;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_99_process
      if (reset == 1'b1) begin
        bit_slicer7_out6_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out6_1 <= bit_slicer7_out6;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_100_process
      if (reset == 1'b1) begin
        bit_slicer8_out6_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out6_1 <= bit_slicer8_out6;
        end
      end
    end


  mux6 u_mux6 (.b0(b0_1),
               .b1(b1_1),
               .b2(b2_1),
               .d1(bit_slicer1_out6_1),  // ufix1
               .d2(bit_slicer2_out6_1),  // ufix1
               .d3(bit_slicer3_out6_1),  // ufix1
               .d4(bit_slicer4_out6_1),  // ufix1
               .d5(bit_slicer5_out6_1),  // ufix1
               .d6(bit_slicer6_out6_1),  // ufix1
               .d7(bit_slicer7_out6_1),  // ufix1
               .d8(bit_slicer8_out6_1),  // ufix1
               .data_out1(mux6_out1)
               );
  always @(posedge clk or posedge reset)
    begin : rd_101_process
      if (reset == 1'b1) begin
        mux6_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux6_out1_1 <= mux6_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_102_process
      if (reset == 1'b1) begin
        bit_slicer1_out5_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out5_1 <= bit_slicer1_out5;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_103_process
      if (reset == 1'b1) begin
        bit_slicer2_out5_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out5_1 <= bit_slicer2_out5;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_104_process
      if (reset == 1'b1) begin
        bit_slicer3_out5_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out5_1 <= bit_slicer3_out5;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_105_process
      if (reset == 1'b1) begin
        bit_slicer4_out5_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out5_1 <= bit_slicer4_out5;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_106_process
      if (reset == 1'b1) begin
        bit_slicer5_out5_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out5_1 <= bit_slicer5_out5;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_107_process
      if (reset == 1'b1) begin
        bit_slicer6_out5_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out5_1 <= bit_slicer6_out5;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_108_process
      if (reset == 1'b1) begin
        bit_slicer7_out5_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out5_1 <= bit_slicer7_out5;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_109_process
      if (reset == 1'b1) begin
        bit_slicer8_out5_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out5_1 <= bit_slicer8_out5;
        end
      end
    end


  mux5 u_mux5 (.b0(b0_1),
               .b1(b1_1),
               .b2(b2_1),
               .d1(bit_slicer1_out5_1),  // ufix1
               .d2(bit_slicer2_out5_1),  // ufix1
               .d3(bit_slicer3_out5_1),  // ufix1
               .d4(bit_slicer4_out5_1),  // ufix1
               .d5(bit_slicer5_out5_1),  // ufix1
               .d6(bit_slicer6_out5_1),  // ufix1
               .d7(bit_slicer7_out5_1),  // ufix1
               .d8(bit_slicer8_out5_1),  // ufix1
               .Out1(mux5_out1)
               );
  always @(posedge clk or posedge reset)
    begin : rd_110_process
      if (reset == 1'b1) begin
        mux5_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux5_out1_1 <= mux5_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_111_process
      if (reset == 1'b1) begin
        bit_slicer1_out4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out4_1 <= bit_slicer1_out4;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_112_process
      if (reset == 1'b1) begin
        bit_slicer2_out4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out4_1 <= bit_slicer2_out4;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_113_process
      if (reset == 1'b1) begin
        bit_slicer3_out4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out4_1 <= bit_slicer3_out4;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_114_process
      if (reset == 1'b1) begin
        bit_slicer4_out4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out4_1 <= bit_slicer4_out4;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_115_process
      if (reset == 1'b1) begin
        bit_slicer5_out4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out4_1 <= bit_slicer5_out4;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_116_process
      if (reset == 1'b1) begin
        bit_slicer6_out4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out4_1 <= bit_slicer6_out4;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_117_process
      if (reset == 1'b1) begin
        bit_slicer7_out4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out4_1 <= bit_slicer7_out4;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_118_process
      if (reset == 1'b1) begin
        bit_slicer8_out4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out4_1 <= bit_slicer8_out4;
        end
      end
    end


  mux4 u_mux4 (.b0(b0_1),
               .b1(b1_1),
               .b2(b2_1),
               .d1(bit_slicer1_out4_1),  // ufix1
               .d2(bit_slicer2_out4_1),  // ufix1
               .d3(bit_slicer3_out4_1),  // ufix1
               .d4(bit_slicer4_out4_1),  // ufix1
               .d5(bit_slicer5_out4_1),  // ufix1
               .d6(bit_slicer6_out4_1),  // ufix1
               .d7(bit_slicer7_out4_1),  // ufix1
               .d8(bit_slicer8_out4_1),  // ufix1
               .data_out1(mux4_out1)
               );
  always @(posedge clk or posedge reset)
    begin : rd_119_process
      if (reset == 1'b1) begin
        mux4_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux4_out1_1 <= mux4_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_120_process
      if (reset == 1'b1) begin
        bit_slicer1_out3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out3_1 <= bit_slicer1_out3;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_121_process
      if (reset == 1'b1) begin
        bit_slicer2_out3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out3_1 <= bit_slicer2_out3;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_122_process
      if (reset == 1'b1) begin
        bit_slicer3_out3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out3_1 <= bit_slicer3_out3;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_123_process
      if (reset == 1'b1) begin
        bit_slicer4_out3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out3_1 <= bit_slicer4_out3;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_124_process
      if (reset == 1'b1) begin
        bit_slicer5_out3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out3_1 <= bit_slicer5_out3;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_125_process
      if (reset == 1'b1) begin
        bit_slicer6_out3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out3_1 <= bit_slicer6_out3;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_126_process
      if (reset == 1'b1) begin
        bit_slicer7_out3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out3_1 <= bit_slicer7_out3;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_127_process
      if (reset == 1'b1) begin
        bit_slicer8_out3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out3_1 <= bit_slicer8_out3;
        end
      end
    end


  mux3 u_mux3 (.b0(b0_1),
               .b1(b1_1),
               .b2(b2_1),
               .d1(bit_slicer1_out3_1),  // ufix1
               .d2(bit_slicer2_out3_1),  // ufix1
               .d3(bit_slicer3_out3_1),  // ufix1
               .d4(bit_slicer4_out3_1),  // ufix1
               .d5(bit_slicer5_out3_1),  // ufix1
               .d6(bit_slicer6_out3_1),  // ufix1
               .d7(bit_slicer7_out3_1),  // ufix1
               .d8(bit_slicer8_out3_1),  // ufix1
               .data_out1(mux3_out1)
               );
  always @(posedge clk or posedge reset)
    begin : rd_128_process
      if (reset == 1'b1) begin
        mux3_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux3_out1_1 <= mux3_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_129_process
      if (reset == 1'b1) begin
        bit_slicer1_out2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out2_1 <= bit_slicer1_out2;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_130_process
      if (reset == 1'b1) begin
        bit_slicer2_out2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out2_1 <= bit_slicer2_out2;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_131_process
      if (reset == 1'b1) begin
        bit_slicer3_out2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out2_1 <= bit_slicer3_out2;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_132_process
      if (reset == 1'b1) begin
        bit_slicer4_out2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out2_1 <= bit_slicer4_out2;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_133_process
      if (reset == 1'b1) begin
        bit_slicer5_out2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out2_1 <= bit_slicer5_out2;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_134_process
      if (reset == 1'b1) begin
        bit_slicer6_out2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out2_1 <= bit_slicer6_out2;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_135_process
      if (reset == 1'b1) begin
        bit_slicer7_out2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out2_1 <= bit_slicer7_out2;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_136_process
      if (reset == 1'b1) begin
        bit_slicer8_out2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out2_1 <= bit_slicer8_out2;
        end
      end
    end


  mux2 u_mux2 (.b0(b0_1),
               .b1(b1_1),
               .b2(b2_1),
               .d1(bit_slicer1_out2_1),  // ufix1
               .d2(bit_slicer2_out2_1),  // ufix1
               .d3(bit_slicer3_out2_1),  // ufix1
               .d4(bit_slicer4_out2_1),  // ufix1
               .d5(bit_slicer5_out2_1),  // ufix1
               .d6(bit_slicer6_out2_1),  // ufix1
               .d7(bit_slicer7_out2_1),  // ufix1
               .d8(bit_slicer8_out2_1),  // ufix1
               .data_out1(mux2_out1)
               );
  always @(posedge clk or posedge reset)
    begin : rd_137_process
      if (reset == 1'b1) begin
        mux2_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux2_out1_1 <= mux2_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_138_process
      if (reset == 1'b1) begin
        bit_slicer1_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer1_out1_1 <= bit_slicer1_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_139_process
      if (reset == 1'b1) begin
        bit_slicer2_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer2_out1_1 <= bit_slicer2_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_140_process
      if (reset == 1'b1) begin
        bit_slicer3_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer3_out1_1 <= bit_slicer3_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_141_process
      if (reset == 1'b1) begin
        bit_slicer4_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer4_out1_1 <= bit_slicer4_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_142_process
      if (reset == 1'b1) begin
        bit_slicer5_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer5_out1_1 <= bit_slicer5_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_143_process
      if (reset == 1'b1) begin
        bit_slicer6_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer6_out1_1 <= bit_slicer6_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_144_process
      if (reset == 1'b1) begin
        bit_slicer7_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer7_out1_1 <= bit_slicer7_out1;
        end
      end
    end


  always @(posedge clk or posedge reset)
    begin : rd_145_process
      if (reset == 1'b1) begin
        bit_slicer8_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          bit_slicer8_out1_1 <= bit_slicer8_out1;
        end
      end
    end


  mux1 u_mux1 (.b0(b0_1),
               .b1(b1_1),
               .b2(b2_1),
               .d1(bit_slicer1_out1_1),  // ufix1
               .d2(bit_slicer2_out1_1),  // ufix1
               .d3(bit_slicer3_out1_1),  // ufix1
               .d4(bit_slicer4_out1_1),  // ufix1
               .d5(bit_slicer5_out1_1),  // ufix1
               .d6(bit_slicer6_out1_1),  // ufix1
               .d7(bit_slicer7_out1_1),  // ufix1
               .d8(bit_slicer8_out1_1),  // ufix1
               .Out1(mux1_out1)
               );
  always @(posedge clk or posedge reset)
    begin : rd_146_process
      if (reset == 1'b1) begin
        mux1_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          mux1_out1_1 <= mux1_out1;
        end
      end
    end


  assign y = {mux16_out1_1, mux15_out1_1, mux14_out1_1, mux13_out1_1, mux12_out1_1, mux11_out1_1, mux10_out1_1, mux9_out1_1, mux8_out1_1, mux7_out1_1, mux6_out1_1, mux5_out1_1, mux4_out1_1, mux3_out1_1, mux2_out1_1, mux1_out1_1};


  assign Delay_One_Step30_ectrl_1 = (d_en_1 == 1'b0 ? Delay_One_Step30_ectrl :
              y);



  always @(posedge clk or posedge reset)
    begin : rd_148_process
      if (reset == 1'b1) begin
        Delay_One_Step30_ectrl <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_One_Step30_ectrl <= Delay_One_Step30_ectrl_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rd_149_process
      if (reset == 1'b1) begin
        Delay_One_Step30_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_One_Step30_out1_1 <= Delay_One_Step30_out1;
        end
      end
    end



  assign Delay_One_Step30_out1 = (d_en_1 == 1'b0 ? Delay_One_Step30_out1_1 :
              Delay_One_Step30_ectrl);



  assign data_out = Delay_One_Step30_out1;

endmodule  // alpha16b_data_transmitter

