// -------------------------------------------------------------
// 
// File Name: C:\Users\earun\Desktop\dcm_new\dcm_4\alpha2level_inverter_hdl1.v
// Created: 2026-05-03 12:29:22
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: alpha2level_inverter_hdl1
// Source Path: dcm_4/PMDC_inv_hdl1/2level_inverter_hdl1
// Hierarchy Level: 1
// Model version: 1.21
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module alpha2level_inverter_hdl1
          (clk,
           reset,
           enb,
           pwma,
           pwmb,
           pwmen,
           Vab);


  input   clk;
  input   reset;
  input   enb;
  input   pwma;
  input   pwmb;
  input   pwmen;
  output  signed [31:0] Vab;  // sfix32_En22


  wire switch_compare_1;
  wire signed [31:0] Constant1_out1;  // sfix32_En22
  reg  pwma_1;
  wire switch_compare_1_1;
  wire signed [31:0] Constant21_out1;  // sfix32_En22
  wire signed [31:0] Vdc_out1;  // sfix32_En22
  wire signed [31:0] Switch_out1;  // sfix32_En22
  reg  pwmb_1;
  wire switch_compare_1_2;
  wire signed [31:0] Switch1_out1;  // sfix32_En22
  wire signed [31:0] Sum2_out1;  // sfix32_En22
  reg signed [31:0] Sum2_out1_1;  // sfix32_En22
  wire signed [31:0] Switch3_out1;  // sfix32_En22


  assign switch_compare_1 = pwmen > 1'b0;



  assign Constant1_out1 = 32'sb00000000000000000000000000000000;


  always @(posedge clk or posedge reset)
    begin : rd_0_process
      if (reset == 1'b1) begin
        pwma_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          pwma_1 <= pwma;
        end
      end
    end



  assign switch_compare_1_1 = pwma_1 > 1'b0;



  assign Constant21_out1 = 32'sb00000000000000000000000000000000;


  assign Vdc_out1 = 32'sb00000110000000000000000000000000;


  assign Switch_out1 = (switch_compare_1_1 == 1'b0 ? Constant21_out1 :
              Vdc_out1);


  always @(posedge clk or posedge reset)
    begin : rd_1_process
      if (reset == 1'b1) begin
        pwmb_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          pwmb_1 <= pwmb;
        end
      end
    end



  assign switch_compare_1_2 = pwmb_1 > 1'b0;



  assign Switch1_out1 = (switch_compare_1_2 == 1'b0 ? Constant21_out1 :
              Vdc_out1);


  assign Sum2_out1 = Switch_out1 - Switch1_out1;


  always @(posedge clk or posedge reset)
    begin : rd_2_process
      if (reset == 1'b1) begin
        Sum2_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Sum2_out1_1 <= Sum2_out1;
        end
      end
    end



  assign Switch3_out1 = (switch_compare_1 == 1'b0 ? Constant1_out1 :
              Sum2_out1_1);


  assign Vab = Switch3_out1;

endmodule  // alpha2level_inverter_hdl1

