// -------------------------------------------------------------
// 
// File Name: C:\Users\earun\Desktop\dcm_new\dcm_4\bit_slicer4.v
// Created: 2026-05-03 12:29:22
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: bit_slicer4
// Source Path: dcm_4/PMDC_inv_hdl1/16b_data_transmitter/bit_slicer4
// Hierarchy Level: 2
// Model version: 1.21
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module bit_slicer4
          (clk,
           reset,
           enb,
           In1,
           y0,
           y1,
           y2,
           y3,
           y4,
           y5,
           y6,
           y7,
           y8,
           y9,
           y10,
           y11,
           y12,
           y13,
           y14,
           y15);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In1;  // sfix16_En12
  output  y0;  // ufix1
  output  y1;  // ufix1
  output  y2;  // ufix1
  output  y3;  // ufix1
  output  y4;  // ufix1
  output  y5;  // ufix1
  output  y6;  // ufix1
  output  y7;  // ufix1
  output  y8;  // ufix1
  output  y9;  // ufix1
  output  y10;  // ufix1
  output  y11;  // ufix1
  output  y12;  // ufix1
  output  y13;  // ufix1
  output  y14;  // ufix1
  output  y15;  // ufix1


  reg signed [15:0] rd_0_reg [0:1];  // sfix16 [2]
  wire signed [15:0] rd_0_reg_next [0:1];  // sfix16_En12 [2]
  wire signed [15:0] In1_1;  // sfix16_En12
  wire Bit_Slice_out1;  // ufix1
  wire Bit_Slice1_out1;  // ufix1
  wire Bit_Slice2_out1;  // ufix1
  wire Bit_Slice3_out1;  // ufix1
  wire Bit_Slice4_out1;  // ufix1
  wire Bit_Slice5_out1;  // ufix1
  wire Bit_Slice6_out1;  // ufix1
  wire Bit_Slice7_out1;  // ufix1
  wire Bit_Slice8_out1;  // ufix1
  wire Bit_Slice9_out1;  // ufix1
  wire Bit_Slice10_out1;  // ufix1
  wire Bit_Slice11_out1;  // ufix1
  wire Bit_Slice12_out1;  // ufix1
  wire Bit_Slice13_out1;  // ufix1
  wire Bit_Slice14_out1;  // ufix1
  wire Bit_Slice15_out1;  // ufix1
  reg signed [31:0] rd_0_t_0_0;  // int32
  reg signed [31:0] rd_0_t_1;  // int32


  always @(posedge clk or posedge reset)
    begin : rd_0_process
      if (reset == 1'b1) begin
        for(rd_0_t_1 = 32'sd0; rd_0_t_1 <= 32'sd1; rd_0_t_1 = rd_0_t_1 + 32'sd1) begin
          rd_0_reg[rd_0_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(rd_0_t_0_0 = 32'sd0; rd_0_t_0_0 <= 32'sd1; rd_0_t_0_0 = rd_0_t_0_0 + 32'sd1) begin
            rd_0_reg[rd_0_t_0_0] <= rd_0_reg_next[rd_0_t_0_0];
          end
        end
      end
    end

  assign In1_1 = rd_0_reg[1];
  assign rd_0_reg_next[0] = In1;
  assign rd_0_reg_next[1] = rd_0_reg[0];



  assign Bit_Slice_out1 = In1_1[0];


  assign y0 = Bit_Slice_out1;

  assign Bit_Slice1_out1 = In1_1[1];


  assign y1 = Bit_Slice1_out1;

  assign Bit_Slice2_out1 = In1_1[2];


  assign y2 = Bit_Slice2_out1;

  assign Bit_Slice3_out1 = In1_1[3];


  assign y3 = Bit_Slice3_out1;

  assign Bit_Slice4_out1 = In1_1[4];


  assign y4 = Bit_Slice4_out1;

  assign Bit_Slice5_out1 = In1_1[5];


  assign y5 = Bit_Slice5_out1;

  assign Bit_Slice6_out1 = In1_1[6];


  assign y6 = Bit_Slice6_out1;

  assign Bit_Slice7_out1 = In1_1[7];


  assign y7 = Bit_Slice7_out1;

  assign Bit_Slice8_out1 = In1_1[8];


  assign y8 = Bit_Slice8_out1;

  assign Bit_Slice9_out1 = In1_1[9];


  assign y9 = Bit_Slice9_out1;

  assign Bit_Slice10_out1 = In1_1[10];


  assign y10 = Bit_Slice10_out1;

  assign Bit_Slice11_out1 = In1_1[11];


  assign y11 = Bit_Slice11_out1;

  assign Bit_Slice12_out1 = In1_1[12];


  assign y12 = Bit_Slice12_out1;

  assign Bit_Slice13_out1 = In1_1[13];


  assign y13 = Bit_Slice13_out1;

  assign Bit_Slice14_out1 = In1_1[14];


  assign y14 = Bit_Slice14_out1;

  assign Bit_Slice15_out1 = In1_1[15];


  assign y15 = Bit_Slice15_out1;

endmodule  // bit_slicer4

