// -------------------------------------------------------------
// 
// File Name: C:\Users\earun\Desktop\dcm_new\dcm_4\mech_model.v
// Created: 2026-05-03 12:29:22
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: mech_model
// Source Path: dcm_4/PMDC_inv_hdl1/PMDC_model1/mech_model
// Hierarchy Level: 2
// Model version: 1.21
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module mech_model
          (clk,
           reset,
           enb,
           Te_in,
           Tl,
           w_o);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] Te_in;  // sfix32_En24
  input   signed [31:0] Tl;  // sfix32_En24
  output  signed [31:0] w_o;  // sfix32_En21


  wire signed [33:0] kconst;  // sfix34_En39
  wire signed [32:0] Sum4_sub_cast;  // sfix33_En24
  wire signed [32:0] Sum4_sub_cast_1;  // sfix33_En24
  wire signed [32:0] Sum4_out1;  // sfix33_En24
  reg signed [32:0] Sum4_out1_1;  // sfix33_En24
  wire signed [33:0] Sum6_add_cast;  // sfix34_En24
  wire signed [33:0] Sum6_add_cast_1;  // sfix34_En24
  wire signed [33:0] Sum6_out1;  // sfix34_En24
  reg signed [33:0] Sum6_out1_1;  // sfix34_En24
  wire signed [67:0] Gain6_mul_temp;  // sfix68_En63
  wire signed [31:0] Gain6_out1;  // sfix32_En21
  reg signed [31:0] Gain6_out1_1;  // sfix32_En21
  reg signed [31:0] Delay2_out1;  // sfix32_En21
  wire signed [31:0] Gain1_out1;  // sfix32_En21
  wire signed [31:0] w_n_1;  // sfix32_En21
  wire signed [63:0] Gain8_mul_temp;  // sfix64_En52
  wire signed [31:0] Gain8_out1;  // sfix32_En21
  reg signed [31:0] Gain8_out1_1;  // sfix32_En21
  wire signed [32:0] Sum5_sub_cast;  // sfix33_En21
  wire signed [32:0] Sum5_sub_cast_1;  // sfix33_En21
  wire signed [32:0] w_n;  // sfix33_En21


  assign kconst = 34'sh12F683799;



  assign Sum4_sub_cast = {Te_in[31], Te_in};
  assign Sum4_sub_cast_1 = {Tl[31], Tl};
  assign Sum4_out1 = Sum4_sub_cast - Sum4_sub_cast_1;


  always @(posedge clk or posedge reset)
    begin : rd_0_process
      if (reset == 1'b1) begin
        Sum4_out1_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          Sum4_out1_1 <= Sum4_out1;
        end
      end
    end



  assign Sum6_add_cast = {Sum4_out1[32], Sum4_out1};
  assign Sum6_add_cast_1 = {Sum4_out1_1[32], Sum4_out1_1};
  assign Sum6_out1 = Sum6_add_cast + Sum6_add_cast_1;


  always @(posedge clk or posedge reset)
    begin : rd_1_process
      if (reset == 1'b1) begin
        Sum6_out1_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Sum6_out1_1 <= Sum6_out1;
        end
      end
    end



  assign Gain6_mul_temp = kconst * Sum6_out1_1;
  assign Gain6_out1 = {{6{Gain6_mul_temp[67]}}, Gain6_mul_temp[67:42]};


  always @(posedge clk or posedge reset)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        Gain6_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Gain6_out1_1 <= Gain6_out1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rd_2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Gain6_out1_1;
        end
      end
    end



  assign w_n_1 = Gain1_out1;
  assign Gain8_mul_temp = 32'sb10000000000000000001000100010110 * w_n_1;
  assign Gain8_out1 = Gain8_mul_temp[62:31];


  always @(posedge clk or posedge reset)
    begin : rd_3_process
      if (reset == 1'b1) begin
        Gain8_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Gain8_out1_1 <= Gain8_out1;
        end
      end
    end



  assign Sum5_sub_cast = {Delay2_out1[31], Delay2_out1};
  assign Sum5_sub_cast_1 = {Gain8_out1_1[31], Gain8_out1_1};
  assign w_n = Sum5_sub_cast - Sum5_sub_cast_1;


  assign Gain1_out1 = w_n[31:0];


  assign w_o = Gain1_out1;

endmodule  // mech_model

