// -------------------------------------------------------------
// 
// File Name: C:\Users\earun\Desktop\dcm_new\dcm_4\mux10.v
// Created: 2026-05-03 12:29:22
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: mux10
// Source Path: dcm_4/PMDC_inv_hdl1/16b_data_transmitter/mux10
// Hierarchy Level: 2
// Model version: 1.21
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module mux10
          (b0,
           b1,
           b2,
           d1,
           d2,
           d3,
           d4,
           d5,
           d6,
           d7,
           d8,
           data_out1);


  input   b0;
  input   b1;
  input   b2;
  input   d1;  // ufix1
  input   d2;  // ufix1
  input   d3;  // ufix1
  input   d4;  // ufix1
  input   d5;  // ufix1
  input   d6;  // ufix1
  input   d7;  // ufix1
  input   d8;  // ufix1
  output  data_out1;


  wire Logical_Operator2_out1;
  wire Logical_Operator3_out1;
  wire Logical_Operator4_out1;
  wire Logical_Operator_out1;
  wire Logical_Operator1_out1;
  wire Logical_Operator5_out1;
  wire Logical_Operator7_out1;
  wire Logical_Operator8_out1;
  wire Logical_Operator9_out1;
  wire Logical_Operator6_out1;
  wire Logical_Operator11_out1;
  wire Logical_Operator10_out1;
  wire Logical_Operator12_out1;
  wire Logical_Operator13_out1;


  assign Logical_Operator2_out1 =  ~ b0;


  assign Logical_Operator3_out1 =  ~ b1;


  assign Logical_Operator4_out1 =  ~ b2;


  assign Logical_Operator_out1 = d1 & (Logical_Operator4_out1 & (Logical_Operator2_out1 & Logical_Operator3_out1));


  assign Logical_Operator1_out1 = d2 & (Logical_Operator4_out1 & (b0 & Logical_Operator3_out1));


  assign Logical_Operator5_out1 = d3 & (Logical_Operator4_out1 & (Logical_Operator2_out1 & b1));


  assign Logical_Operator7_out1 = d5 & (b2 & (Logical_Operator2_out1 & Logical_Operator3_out1));


  assign Logical_Operator8_out1 = d6 & (b2 & (b0 & Logical_Operator3_out1));


  assign Logical_Operator9_out1 = d7 & (b2 & (Logical_Operator2_out1 & b1));


  assign Logical_Operator6_out1 = d4 & (Logical_Operator4_out1 & (b0 & b1));


  assign Logical_Operator11_out1 = Logical_Operator6_out1 | (Logical_Operator5_out1 | (Logical_Operator_out1 | Logical_Operator1_out1));


  assign Logical_Operator10_out1 = d8 & (b2 & (b0 & b1));


  assign Logical_Operator12_out1 = Logical_Operator10_out1 | (Logical_Operator9_out1 | (Logical_Operator7_out1 | Logical_Operator8_out1));


  assign Logical_Operator13_out1 = Logical_Operator11_out1 | Logical_Operator12_out1;


  assign data_out1 = Logical_Operator13_out1;

endmodule  // mux10

