// -------------------------------------------------------------
// 
// File Name: C:\Users\earun\Desktop\dcm_new\dcm_4\PMDC_inv_hdl1.v
// Created: 2026-05-03 12:29:22
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-05
// Target subsystem base rate: 1e-05
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1e-05
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// data_out                      ce_out        1e-05
// T_x0                          ce_out        1e-05
// T_x1                          ce_out        1e-05
// PWMen_o                       ce_out        1e-05
// ia_out_tcp                    ce_out        1e-05
// w_out_tcp                     ce_out        1e-05
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PMDC_inv_hdl1
// Source Path: dcm_4/PMDC_inv_hdl1
// Hierarchy Level: 0
// Model version: 1.21
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PMDC_inv_hdl1
          (clk,
           reset,
           clk_enable,
           pwma,
           pwmb,
           pwmen,
           b0,
           b1,
           b2,
           d_en,
           Tl0,
           Tl1,
           Tl2,
           ce_out,
           data_out,
           T_x0,
           T_x1,
           PWMen_o,
           ia_out_tcp,
           w_out_tcp);


  input   clk;
  input   reset;
  input   clk_enable;
  input   pwma;
  input   pwmb;
  input   pwmen;
  input   b0;
  input   b1;
  input   b2;
  input   d_en;
  input   Tl0;
  input   Tl1;
  input   Tl2;
  output  ce_out;
  output  [15:0] data_out;  // uint16
  output  T_x0;
  output  T_x1;
  output  PWMen_o;
  output  signed [15:0] ia_out_tcp;  // sfix16_En12
  output  signed [15:0] w_out_tcp;  // sfix16_En12


  wire enb;
  wire signed [31:0] alpha2level_inverter_hdl1_out1;  // sfix32_En22
  reg signed [31:0] alpha2level_inverter_hdl1_out1_1;  // sfix32_En22
  wire signed [31:0] test3;  // sfix32_En24
  wire signed [31:0] test3_1;  // sfix32_En24
  wire signed [15:0] w_n_1;  // sfix16_En12
  wire signed [15:0] w_n_1_1;  // sfix16_En12
  wire [15:0] alpha16b_data_transmitter_out1;  // uint16
  reg  Tl0_1;
  reg  Tl1_1;
  reg  pwmen_1;
  reg signed [15:0] w_n_1_2;  // sfix16_En12
  reg signed [15:0] w_n_1_3;  // sfix16_En12

  // to zynq PS
  // to zynq PS
  // to controller


  alpha2level_inverter_hdl1 u_2level_inverter_hdl1 (.clk(clk),
                                                    .reset(reset),
                                                    .enb(clk_enable),
                                                    .pwma(pwma),
                                                    .pwmb(pwmb),
                                                    .pwmen(pwmen),
                                                    .Vab(alpha2level_inverter_hdl1_out1)  // sfix32_En22
                                                    );
  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : rd_0_process
      if (reset == 1'b1) begin
        alpha2level_inverter_hdl1_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          alpha2level_inverter_hdl1_out1_1 <= alpha2level_inverter_hdl1_out1;
        end
      end
    end


  torque_input u_torque_input (.clk(clk),
                               .reset(reset),
                               .enb(clk_enable),
                               .T_0(Tl0),
                               .T_1(Tl1),
                               .T_2(Tl2),
                               .Out1(test3)  // sfix32_En24
                               );
  assign test3_1 = test3;
  PMDC_model1 u_PMDC_model1 (.clk(clk),
                             .reset(reset),
                             .enb(clk_enable),
                             .Vab(alpha2level_inverter_hdl1_out1_1),  // sfix32_En22
                             .Tl(test3_1),  // sfix32_En24
                             .ia_out(w_n_1),  // sfix16_En12
                             .w_out(w_n_1_1)  // sfix16_En12
                             );
  alpha16b_data_transmitter u_16b_data_transmitter (.clk(clk),
                                                    .reset(reset),
                                                    .enb(clk_enable),
                                                    .b2(b2),
                                                    .b1(b1),
                                                    .b0(b0),
                                                    .d_en(d_en),
                                                    .ia_out(w_n_1),  // sfix16_En12
                                                    .w_out(w_n_1_1),  // sfix16_En12
                                                    .In88(w_n_1),  // sfix16_En12
                                                    .In90(w_n_1_1),  // sfix16_En12
                                                    .In10(w_n_1),  // sfix16_En12
                                                    .In87(w_n_1_1),  // sfix16_En12
                                                    .In89(w_n_1),  // sfix16_En12
                                                    .In91(w_n_1_1),  // sfix16_En12
                                                    .data_out(alpha16b_data_transmitter_out1)  // uint16
                                                    );
  assign data_out = alpha16b_data_transmitter_out1;

  always @(posedge clk or posedge reset)
    begin : rd_1_process
      if (reset == 1'b1) begin
        Tl0_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Tl0_1 <= Tl0;
        end
      end
    end



  assign T_x0 = Tl0_1;

  always @(posedge clk or posedge reset)
    begin : rd_2_process
      if (reset == 1'b1) begin
        Tl1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Tl1_1 <= Tl1;
        end
      end
    end



  assign T_x1 = Tl1_1;

  always @(posedge clk or posedge reset)
    begin : rd_3_process
      if (reset == 1'b1) begin
        pwmen_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          pwmen_1 <= pwmen;
        end
      end
    end



  assign PWMen_o = pwmen_1;

  always @(posedge clk or posedge reset)
    begin : rd_4_process
      if (reset == 1'b1) begin
        w_n_1_2 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          w_n_1_2 <= w_n_1;
        end
      end
    end



  assign ia_out_tcp = w_n_1_2;

  always @(posedge clk or posedge reset)
    begin : rd_5_process
      if (reset == 1'b1) begin
        w_n_1_3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          w_n_1_3 <= w_n_1_1;
        end
      end
    end



  assign w_out_tcp = w_n_1_3;

  assign ce_out = clk_enable;

endmodule  // PMDC_inv_hdl1

