// -------------------------------------------------------------
// 
// File Name: C:\Users\earun\Desktop\dcm_new\dcm_4\PMDC_model1.v
// Created: 2026-05-03 12:29:22
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PMDC_model1
// Source Path: dcm_4/PMDC_inv_hdl1/PMDC_model1
// Hierarchy Level: 1
// Model version: 1.21
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PMDC_model1
          (clk,
           reset,
           enb,
           Vab,
           Tl,
           ia_out,
           w_out);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] Vab;  // sfix32_En22
  input   signed [31:0] Tl;  // sfix32_En24
  output  signed [15:0] ia_out;  // sfix16_En12
  output  signed [15:0] w_out;  // sfix16_En12


  wire signed [31:0] Constant_out1;  // sfix32_En24
  wire signed [31:0] ian_1;  // sfix32_En24
  wire signed [31:0] Torque_model_out1;  // sfix32_En24
  wire signed [31:0] w_n_1;  // sfix32_En21
  wire signed [31:0] w_n_1_1;  // sfix32_En24
  wire signed [63:0] Gain4_cast;  // sfix64_En60
  wire signed [15:0] Gain4_out1;  // sfix16_En12
  wire signed [15:0] w_n_1_2;  // sfix16_En12
  wire signed [31:0] w_n_1_3;  // sfix32_En21
  reg signed [31:0] w_n_1_4;  // sfix32_En21
  wire signed [63:0] Gain1_cast;  // sfix64_En58
  wire signed [15:0] Gain1_out1;  // sfix16_En12
  wire signed [15:0] w_n_1_5;  // sfix16_En12


  assign Constant_out1 = 32'sb00000000000010011011101001011110;


  Torque_model u_Torque_model (.clk(clk),
                               .reset(reset),
                               .enb(enb),
                               .ia(ian_1),  // sfix32_En24
                               .kt(Constant_out1),  // sfix32_En24
                               .Te(Torque_model_out1)  // sfix32_En24
                               );
  mech_model u_mech_model (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .Te_in(Torque_model_out1),  // sfix32_En24
                           .Tl(Tl),  // sfix32_En24
                           .w_o(w_n_1)  // sfix32_En21
                           );
  voltage_model_q u_voltage_model_q (.clk(clk),
                                     .reset(reset),
                                     .enb(enb),
                                     .Va(Vab),  // sfix32_En22
                                     .win(w_n_1),  // sfix32_En21
                                     .ia_out(ian_1)  // sfix32_En24
                                     );
  assign w_n_1_1 = ian_1;
  assign Gain4_cast = {{2{w_n_1_1[31]}}, {w_n_1_1, 30'b000000000000000000000000000000}};
  assign Gain4_out1 = Gain4_cast[63:48];


  assign w_n_1_2 = Gain4_out1;
  assign ia_out = w_n_1_2;

  assign w_n_1_3 = w_n_1;
  always @(posedge clk or posedge reset)
    begin : rd_0_process
      if (reset == 1'b1) begin
        w_n_1_4 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          w_n_1_4 <= w_n_1_3;
        end
      end
    end



  assign Gain1_cast = {{2{w_n_1_4[31]}}, {w_n_1_4, 30'b000000000000000000000000000000}};
  assign Gain1_out1 = Gain1_cast[61:46];


  assign w_n_1_5 = Gain1_out1;
  assign w_out = w_n_1_5;

endmodule  // PMDC_model1

