// -------------------------------------------------------------
// 
// File Name: C:\Users\earun\Desktop\dcm_new\dcm_4\Torque_model.v
// Created: 2026-05-03 12:29:22
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Torque_model
// Source Path: dcm_4/PMDC_inv_hdl1/PMDC_model1/Torque_model
// Hierarchy Level: 2
// Model version: 1.21
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Torque_model
          (clk,
           reset,
           enb,
           ia,
           kt,
           Te);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] ia;  // sfix32_En24
  input   signed [31:0] kt;  // sfix32_En24
  output  signed [31:0] Te;  // sfix32_En24


  reg signed [31:0] kt_1;  // sfix32_En24
  wire signed [63:0] Product_out1;  // sfix64_En48
  wire signed [31:0] Data_Type_Conversion1_out1;  // sfix32_En24
  reg signed [31:0] rd_1_reg [0:1];  // sfix32 [2]
  wire signed [31:0] rd_1_reg_next [0:1];  // sfix32_En24 [2]
  wire signed [31:0] Data_Type_Conversion1_out1_1;  // sfix32_En24
  reg signed [31:0] rd_1_t_0_0;  // int32
  reg signed [31:0] rd_1_t_1;  // int32


  always @(posedge clk or posedge reset)
    begin : rd_0_process
      if (reset == 1'b1) begin
        kt_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          kt_1 <= kt;
        end
      end
    end



  assign Product_out1 = ia * kt_1;


  assign Data_Type_Conversion1_out1 = Product_out1[55:24];


  always @(posedge clk or posedge reset)
    begin : rd_1_process
      if (reset == 1'b1) begin
        for(rd_1_t_1 = 32'sd0; rd_1_t_1 <= 32'sd1; rd_1_t_1 = rd_1_t_1 + 32'sd1) begin
          rd_1_reg[rd_1_t_1] <= 32'sb00000000000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(rd_1_t_0_0 = 32'sd0; rd_1_t_0_0 <= 32'sd1; rd_1_t_0_0 = rd_1_t_0_0 + 32'sd1) begin
            rd_1_reg[rd_1_t_0_0] <= rd_1_reg_next[rd_1_t_0_0];
          end
        end
      end
    end

  assign Data_Type_Conversion1_out1_1 = rd_1_reg[1];
  assign rd_1_reg_next[0] = Data_Type_Conversion1_out1;
  assign rd_1_reg_next[1] = rd_1_reg[0];


  assign Te = Data_Type_Conversion1_out1_1;

endmodule  // Torque_model

