// -------------------------------------------------------------
// 
// File Name: C:\Users\earun\Desktop\dcm_new\dcm_4\torque_input.v
// Created: 2026-05-03 12:29:22
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: torque_input
// Source Path: dcm_4/PMDC_inv_hdl1/torque_input
// Hierarchy Level: 1
// Model version: 1.21
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module torque_input
          (clk,
           reset,
           enb,
           T_0,
           T_1,
           T_2,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   T_0;
  input   T_1;
  input   T_2;
  output  signed [31:0] Out1;  // sfix32_En24


  reg  T_2_1;
  reg  T_1_1;
  reg  T_0_1;
  wire [2:0] y;  // ufix3
  reg [2:0] y_1;  // ufix3
  wire signed [31:0] Ta_out1;  // sfix32_En24
  wire signed [31:0] Tb_out1;  // sfix32_En24
  reg signed [31:0] Tb_out1_1;  // sfix32_En24
  wire signed [31:0] Tc_out1;  // sfix32_En24
  reg signed [31:0] Tc_out1_1;  // sfix32_En24
  wire signed [31:0] Td_out1;  // sfix32_En24
  reg signed [31:0] Td_out1_1;  // sfix32_En24
  wire signed [31:0] Ta1_out1;  // sfix32_En24
  reg signed [31:0] Ta1_out1_1;  // sfix32_En24
  wire signed [31:0] Tb1_out1;  // sfix32_En24
  reg signed [31:0] Tb1_out1_1;  // sfix32_En24
  wire signed [31:0] Tc1_out1;  // sfix32_En24
  reg signed [31:0] Tc1_out1_1;  // sfix32_En24
  wire signed [31:0] Td1_out1;  // sfix32_En24
  wire signed [31:0] test3;  // sfix32_En24


  always @(posedge clk or posedge reset)
    begin : rd_0_process
      if (reset == 1'b1) begin
        T_2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          T_2_1 <= T_2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rd_1_process
      if (reset == 1'b1) begin
        T_1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          T_1_1 <= T_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rd_2_process
      if (reset == 1'b1) begin
        T_0_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          T_0_1 <= T_0;
        end
      end
    end



  assign y = {T_2_1, T_1_1, T_0_1};


  always @(posedge clk or posedge reset)
    begin : rd_3_process
      if (reset == 1'b1) begin
        y_1 <= 3'b000;
      end
      else begin
        if (enb) begin
          y_1 <= y;
        end
      end
    end



  assign Ta_out1 = 32'sb00000000000000000000000000000000;


  assign Tb_out1 = 32'sb00000000000011001100110011001101;


  always @(posedge clk or posedge reset)
    begin : rd_4_process
      if (reset == 1'b1) begin
        Tb_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Tb_out1_1 <= Tb_out1;
        end
      end
    end



  assign Tc_out1 = 32'sb00000000000110011001100110011010;


  always @(posedge clk or posedge reset)
    begin : rd_5_process
      if (reset == 1'b1) begin
        Tc_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Tc_out1_1 <= Tc_out1;
        end
      end
    end



  assign Td_out1 = 32'sb00000000001001100110011001100110;


  always @(posedge clk or posedge reset)
    begin : rd_6_process
      if (reset == 1'b1) begin
        Td_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Td_out1_1 <= Td_out1;
        end
      end
    end



  assign Ta1_out1 = 32'sb11111111111100110011001100110011;


  always @(posedge clk or posedge reset)
    begin : rd_7_process
      if (reset == 1'b1) begin
        Ta1_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Ta1_out1_1 <= Ta1_out1;
        end
      end
    end



  assign Tb1_out1 = 32'sb11111111111001100110011001100110;


  always @(posedge clk or posedge reset)
    begin : rd_8_process
      if (reset == 1'b1) begin
        Tb1_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Tb1_out1_1 <= Tb1_out1;
        end
      end
    end



  assign Tc1_out1 = 32'sb11111111110110011001100110011010;


  always @(posedge clk or posedge reset)
    begin : rd_9_process
      if (reset == 1'b1) begin
        Tc1_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Tc1_out1_1 <= Tc1_out1;
        end
      end
    end



  assign Td1_out1 = 32'sb00000000000000000000000000000000;


  assign test3 = (y_1 == 3'b000 ? Ta_out1 :
              (y_1 == 3'b001 ? Tb_out1_1 :
              (y_1 == 3'b010 ? Tc_out1_1 :
              (y_1 == 3'b011 ? Td_out1_1 :
              (y_1 == 3'b100 ? Ta1_out1_1 :
              (y_1 == 3'b101 ? Tb1_out1_1 :
              (y_1 == 3'b110 ? Tc1_out1_1 :
              Td1_out1)))))));


  assign Out1 = test3;

endmodule  // torque_input

