// -------------------------------------------------------------
// 
// File Name: C:\Users\earun\Desktop\dcm_new\dcm_4\voltage_model_q.v
// Created: 2026-05-03 12:29:22
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: voltage_model_q
// Source Path: dcm_4/PMDC_inv_hdl1/PMDC_model1/voltage_model_q
// Hierarchy Level: 2
// Model version: 1.21
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module voltage_model_q
          (clk,
           reset,
           enb,
           Va,
           win,
           ia_out);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] Va;  // sfix32_En22
  input   signed [31:0] win;  // sfix32_En21
  output  signed [31:0] ia_out;  // sfix32_En24


  wire signed [33:0] kconst;  // sfix34_En43
  reg signed [33:0] kconst_1;  // sfix34_En43
  reg signed [31:0] win_1;  // sfix32_En21
  wire signed [63:0] Gain2_mul_temp;  // sfix64_En56
  wire signed [31:0] Gain2_out1;  // sfix32_En22
  wire signed [32:0] Sum1_sub_cast;  // sfix33_En22
  wire signed [32:0] Sum1_sub_cast_1;  // sfix33_En22
  wire signed [32:0] Sum1_sub_temp;  // sfix33_En22
  wire signed [32:0] Sum1_out1;  // sfix33_En24
  reg signed [32:0] Sum1_out1_1;  // sfix33_En24
  reg signed [32:0] Sum1_out1_2;  // sfix33_En24
  wire signed [33:0] Sum3_add_cast;  // sfix34_En24
  wire signed [33:0] Sum3_add_cast_1;  // sfix34_En24
  wire signed [33:0] Sum3_out1;  // sfix34_En24
  reg signed [33:0] Sum3_out1_1;  // sfix34_En24
  wire signed [67:0] Gain4_mul_temp;  // sfix68_En67
  wire signed [31:0] Gain4_out1;  // sfix32_En24
  reg signed [31:0] Gain4_out1_1;  // sfix32_En24
  reg signed [31:0] Delay5_out1;  // sfix32_En24
  wire signed [31:0] Gain1_out1;  // sfix32_En24
  wire signed [31:0] ian_1;  // sfix32_En24
  wire signed [63:0] Gain5_mul_temp;  // sfix64_En55
  wire signed [31:0] Gain5_out1;  // sfix32_En24
  reg signed [31:0] Gain5_out1_1;  // sfix32_En24
  wire signed [32:0] Sum2_sub_cast;  // sfix33_En24
  wire signed [32:0] Sum2_sub_cast_1;  // sfix33_En24
  wire signed [32:0] ian;  // sfix33_En24


  assign kconst = 34'sh19978D79D;



  always @(posedge clk or posedge reset)
    begin : rd_3_process
      if (reset == 1'b1) begin
        kconst_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          kconst_1 <= kconst;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rd_0_process
      if (reset == 1'b1) begin
        win_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          win_1 <= win;
        end
      end
    end



  assign Gain2_mul_temp = 32'sb01001101110100101111000110101010 * win_1;
  assign Gain2_out1 = {{2{Gain2_mul_temp[63]}}, Gain2_mul_temp[63:34]};


  assign Sum1_sub_cast = {Va[31], Va};
  assign Sum1_sub_cast_1 = {Gain2_out1[31], Gain2_out1};
  assign Sum1_sub_temp = Sum1_sub_cast - Sum1_sub_cast_1;
  assign Sum1_out1 = {Sum1_sub_temp[30:0], 2'b00};


  always @(posedge clk or posedge reset)
    begin : rd_1_process
      if (reset == 1'b1) begin
        Sum1_out1_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          Sum1_out1_1 <= Sum1_out1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rd_2_process
      if (reset == 1'b1) begin
        Sum1_out1_2 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          Sum1_out1_2 <= Sum1_out1_1;
        end
      end
    end



  assign Sum3_add_cast = {Sum1_out1_1[32], Sum1_out1_1};
  assign Sum3_add_cast_1 = {Sum1_out1_2[32], Sum1_out1_2};
  assign Sum3_out1 = Sum3_add_cast + Sum3_add_cast_1;


  always @(posedge clk or posedge reset)
    begin : rd_4_process
      if (reset == 1'b1) begin
        Sum3_out1_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Sum3_out1_1 <= Sum3_out1;
        end
      end
    end



  assign Gain4_mul_temp = kconst_1 * Sum3_out1_1;
  assign Gain4_out1 = {{7{Gain4_mul_temp[67]}}, Gain4_mul_temp[67:43]};


  always @(posedge clk or posedge reset)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        Gain4_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Gain4_out1_1 <= Gain4_out1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rd_5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay5_out1 <= Gain4_out1_1;
        end
      end
    end



  assign ian_1 = Gain1_out1;
  assign Gain5_mul_temp = 32'sb10000000000101000111100100111110 * ian_1;
  assign Gain5_out1 = Gain5_mul_temp[62:31];


  always @(posedge clk or posedge reset)
    begin : rd_6_process
      if (reset == 1'b1) begin
        Gain5_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Gain5_out1_1 <= Gain5_out1;
        end
      end
    end



  assign Sum2_sub_cast = {Delay5_out1[31], Delay5_out1};
  assign Sum2_sub_cast_1 = {Gain5_out1_1[31], Gain5_out1_1};
  assign ian = Sum2_sub_cast - Sum2_sub_cast_1;


  assign Gain1_out1 = ian[31:0];


  assign ia_out = Gain1_out1;

endmodule  // voltage_model_q

